// <auto-generated />
using System;
using Dab_aflevering_2.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dab_aflevering_2.Migrations
{
    [DbContext(typeof(DabDBContext))]
    partial class DabDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20159.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dab_aflevering_2.Entities.AssignmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.AssignmentStudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignmentsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentAuId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("AssignmentStudents");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentEntityId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.ExerciseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HelpWhere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lecture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.StudentCourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("StudentAuId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoursesId");

                    b.HasIndex("StudentsId");

                    b.ToTable("StudentsCourses");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.StudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.TeacherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.AssignmentEntity", b =>
                {
                    b.HasOne("Dab_aflevering_2.Entities.CourseEntity", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId");

                    b.HasOne("Dab_aflevering_2.Entities.TeacherEntity", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.AssignmentStudentEntity", b =>
                {
                    b.HasOne("Dab_aflevering_2.Entities.AssignmentEntity", "Assignments")
                        .WithMany("Students")
                        .HasForeignKey("AssignmentsId");

                    b.HasOne("Dab_aflevering_2.Entities.StudentEntity", "Students")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentsId");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.CourseEntity", b =>
                {
                    b.HasOne("Dab_aflevering_2.Entities.StudentEntity", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentEntityId");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.ExerciseEntity", b =>
                {
                    b.HasOne("Dab_aflevering_2.Entities.StudentEntity", "Student")
                        .WithMany("Exercises")
                        .HasForeignKey("StudentId");

                    b.HasOne("Dab_aflevering_2.Entities.TeacherEntity", "Teacher")
                        .WithMany("Exercises")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.StudentCourseEntity", b =>
                {
                    b.HasOne("Dab_aflevering_2.Entities.CourseEntity", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CoursesId");

                    b.HasOne("Dab_aflevering_2.Entities.StudentEntity", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsId");
                });

            modelBuilder.Entity("Dab_aflevering_2.Entities.TeacherEntity", b =>
                {
                    b.HasOne("Dab_aflevering_2.Entities.CourseEntity", "Course")
                        .WithMany("Teachers")
                        .HasForeignKey("CourseId");
                });
#pragma warning restore 612, 618
        }
    }
}
